project:
  type: website
  output-dir: docs

website:
  title: "dawn-cheung"
  navbar:
    left:
      - href: index.qmd #hret hyperlinks the file
        text: Home #hret change the name of the tab
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

